site_name: AutoDocs
theme:
    name: material
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    members_order: alphabetical
                    show_source: true
                    docstring_style: google
                    filters:
                    - ""
nav:
    - Home: index.md